### ISSUE TITLE
Suggestion : Profiles.

### ISSUE THREAD

**Issue by Feary** [erupt321/curtracker#1]
Just an idea or suggestion. the Ability to create profiles would nice. 

An example  of a Profile would be Named: Mythic. with tokens, another profile for synthesis with crystal/spheres, a profile with just rem tales 1-10, while a default profile can have sparks, login points. etc

**Comment by erupt321** [comment]
That's a cool idea, I'll sit down and make some categories, should be pretty quick to do.

**Comment by erupt321** [comment]
Added profiles in latest version now.  Will update profiles.lua with some more options a little later.
